### ISSUE TITLE
publish dbt docs to github pages?

### ISSUE THREAD

**Issue by matsonj** [C00ldudeNoonan/simple-dbt-runner#12]
If we want, we can set up dbt docs to publish to github pages. Which is a neat trick, probably not super relevant for most projects though bc unless you are using github enterprise you can’t add access control to them. Or we could publish to the web via AWS? Or Netlify? Thoughts?

**Comment by mermelstein** [comment]
I like the AWS route. Static pages on S3 are my favorite but adding SSO is also a pain so not sure it's worth it to get too deep into it beyond just pointing out that it's possible and extend [upload_to_s3.py](https://github.com/C00ldudeNoonan/simple-dbt-runner/pull/6/files#diff-826cf2443f8532ea97951c28903bc6d1b26d3ab9e493a0920129c671dcc97286) to also push the `index.html` and `catalog.json`

**Comment by matsonj** [comment]
Yeah I think since we already using S3, this makes a ton of sense. I’ve actually never done static pages on S3 so excited to see how to do that.

**Comment by C00ldudeNoonan** [comment]
I can start working on a cloud formation template for a bucket for static hosting and a iam user with access keys.

**Comment by matsonj** [comment]
Approved

**Comment by C00ldudeNoonan** [comment]
Created an S3 bucket for hosting the docs -> http://dbt-s3bucket-eywrs70vvmxj.s3-website-us-east-1.amazonaws.com/ and added the secrets and bucket names to the repo enviroment variables.
