### ISSUE TITLE
Github bot permissions

### ISSUE THREAD

**Issue by mermelstein** [C00ldudeNoonan/simple-dbt-runner#13]
Ok so turns out in order for GH Actions to open PRs we also need to select that the base GITHUB_TOKEN should have read and write permissions. I tested separately and if that gets updated we can successfully run the `Project Setup` workflow.

<img width="779" alt="Screenshot 2023-08-29 at 2 01 33 PM" src="https://github.com/C00ldudeNoonan/simple-dbt-runner/assets/21294829/512bf335-6796-4ae3-a7dc-ad1cf6c4035f">

**Comment by C00ldudeNoonan** [comment]
Just updated and project workflow ran successfully.
