### ISSUE TITLE
Replace docs deploy with cloudformation with github action

### ISSUE THREAD

**Issue by matsonj** [C00ldudeNoonan/simple-dbt-runner#17]
https://github.com/dwreeves/dbt_docs_ghpages_example/blob/main/.github/workflows/docs.yml

Happy to implement this gh action - but I think @C00ldudeNoonan needs to do this since it is his repo.

We also need to disable the public s3 doc pages.

I’ll just drop this in a checklist:

- [x] @C00ldudeNoonan add github action and test that the github pages build
- [x] @mermelstein clean up s3 pages build scripts + cloudformation templates

**Comment by mermelstein** [comment]
Say hello to my little friend: https://github.com/C00ldudeNoonan/simple-dbt-runner/pull/18

I think the PR removes the need for an additional GH Action, simply integrated into our existing workflows. Needs to be tested

**Comment by matsonj** [comment]
Yeah that makes sense. No notes on your implementation of your solution. 

I'll update the readme!

**Comment by matsonj** [comment]
TODO

- [x]  update README to reflect these changes and how/who can put docs behind SSO
- [x]  credit https://github.com/dwreeves/dbt_docs_ghpages_example in README

**Comment by matsonj** [comment]
Closing these tasks on with #19

**Comment by matsonj** [comment]
@C00ldudeNoonan you're up for github pages config.

**Comment by C00ldudeNoonan** [comment]
Got the page to deploy https://c00ldudenoonan.github.io/simple-dbt-runner/#!/overview. I'll work on merging the branch to main and updating the page settings.
