### ISSUE TITLE
GH action failing: manifest.sh

### ISSUE THREAD

**Issue by matsonj** [C00ldudeNoonan/simple-dbt-runner#20]
https://github.com/C00ldudeNoonan/simple-dbt-runner/actions/runs/6291708765/job/17080343847

`/home/runner/work/_temp/660235aa-1d98-43a2-82c1-4816e4a93fed.sh: line 1: get_manifest.sh: command not found`

Not sure why the github action cannot see `get_manifest.sh` - this is the worst part of using github actions

**Comment by mermelstein** [comment]
This issue is fixed, now trying to get it to see the `gh-pages` branch to pull the manifest.json from
https://github.com/C00ldudeNoonan/simple-dbt-runner/actions/runs/6293140305/job/17083255958
