### ISSUE TITLE
actions not running

### ISSUE THREAD

**Issue by mermelstein** [C00ldudeNoonan/simple-dbt-runner#23]
eg https://github.com/C00ldudeNoonan/simple-dbt-runner/actions/runs/6325746905/job/17177904188

looks like there's an issue with the db connection -> running the repo locally works fine, as well as manual local db connections from multiple IP addresses. @C00ldudeNoonan did we do anything with the repo secrets last night that could cause this?

Also seems like maybe something similar has happened before? See this old issue: https://github.com/orgs/community/discussions/25701

**Comment by C00ldudeNoonan** [comment]
I updated the prod password instead of the prod schema last night. As they say skill issue. Everything is running fine now.
