### ISSUE TITLE
define github actions

### ISSUE THREAD

**Issue by matsonj** [C00ldudeNoonan/simple-dbt-runner#3]
we need to define some actions, i recommend the following.

- [x] manual dbt build
- [x] manual dbt run (for emergency reasons)
- [x] run on pull request (on dedicated pr branch)
- [x] run on merge
- [x] run on a cron

**Comment by matsonj** [comment]
first order of business is to the dbt action to actually see the `dbt_profiles.yml` file

**Comment by mermelstein** [comment]
`manual dbt run (for emergency reasons)` are we thinking like running specific models in prod or dev? Feel like we should stay away from dev stuff in this project

**Comment by matsonj** [comment]
I’m cloning dev to prod, they can be dupes for this so that everything runs fine.
