### ISSUE TITLE
Use dbt build instead of dbt run (don’t use dbt run you maniacs)

### ISSUE THREAD

**Issue by matsonj** [C00ldudeNoonan/simple-dbt-runner#7]
We should use `dbt build` whenever possible instead of `dbt seed` + `dbt run` + `dbt test`. 

dbt build is better than dbt test because it will fail downstream models from building, that way instead of getting bad data in prod, it just gets delayed.

**Comment by mermelstein** [comment]
😄

**Comment by matsonj** [comment]
Ok this is annoying, we don’t have seperate secrets for Dev & prod, so I am going to commit this change using prod == dev but I am going to add an addtl issue for adding those secrets. I don’t have ability to do it.
