### ISSUE TITLE
Add secrets for dev env

### ISSUE THREAD

**Issue by matsonj** [C00ldudeNoonan/simple-dbt-runner#9]
We need creds dev env, so we can run something in the dev env on PR.

Need the following Secrets

DEV_USERNAME
DEV_PASSWORD
DEV_SCHEMA

**Comment by matsonj** [comment]
@C00ldudeNoonan  also take a look at #11, we can take this approach instead if you think it is better?

**Comment by mermelstein** [comment]
for the dev user/pass secrets we could just use the prod secrets, right? Only thing that needs to be different is DEV_SCHEMA for testing I think?

**Comment by C00ldudeNoonan** [comment]
Just updated
